### ISSUE TITLE
Feature-4 버그 

### ISSUE THREAD

**Issue by dpdltm2944** [kanggeonnim/LBDRWT#49]
index.js 
학과 안내 입력 시 -> im alive
학과 입력 시 -> 정상 작동
학사 일정 입력 시 -> im alive
학사 입력 시 -> 정상 작동
 
/^학사?[ ]?[일정]?$/.test(text) - >  /^학사?[ ]?일정$/.test(text)
변경 후 학과 안내 입력 시 정상 작동

해결 필요

**Comment by kanggeonnim** [comment]
/학사[ ]?일정/
/학과[ ]?안내/
로 수정하여 오류 해결하였습니다.
